version: '3.4'

services:
  web:
    build:
      context: .
      target: base
    entrypoint: ["/rails/bin/docker-entrypoint.sh"]
    command: bin/rails server -b 0.0.0.0
    volumes:
      - .:/rails
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - redis
  worker:
    build:
      context: .
      target: base
    command: bundle exec sidekiq
    volumes:
      - .:/rails
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: postgres
  redis:
    image: redis:6
