default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: postgres
  username: postgres
  password: postgres
  database: app_development

test:
  <<: *default
  host: postgres
  username: postgres
  password: postgres
  database: app_test

# DATABASE_URL="postgres://myuser:mypass@localhost/somedatabase"
production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
